services:
  # A Docker web service
  - type: web
    name: AList+Aria2
    env: docker
    repo: https://github.com/Alexander-Porter/AList-Aria2-Render.git # optional
    region: Singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 5244
      - key: DB_TYPE
        value: postgres
        #sync: false
      - key: DB_HOST
        value: db.bit.io
        #sync: false
      - key: DB_PORT
        value: 5432
        #sync: false
      - key: DB_USER
        value: alist
        #sync: false
      - key: DB_PASS
        value: v2_3xkBG_RM3WsyGjdeRPudtk3kXkYw3
        #sync: false
      - key: DB_NAME
        value: Alexander-Porter/trial
        #sync: false
      - key: DB_TABLE_PREFIX
        value: alist_
        #sync: false
